### ISSUE TITLE
[Incorrect Remote] android_device_qcom_common

### ISSUE THREAD

**Issue by berryman13** [Vexxo/manifest#1]
Line 557:  <project path="device/qcom/common" name="device_qcom_common" remote="vx" revision="vx5.1" />

The Vexxo github does not have a device_qcom_common repository, thus it is currently unable to complete an initialization/sync.

**Comment by GalaticStryder** [comment]
I'm working on a big update, needs a lot of stuff. Don't sync it yet.

**Comment by berryman13** [comment]
Lets chat on hangouts. It's too late for that my friend!

**Comment by GalaticStryder** [comment]
Issue solved, just sync it, it won't build yet though until I push some more fixes to match the frameworks into Settings, MMS and Vendor.
